name: Rust Debug Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        # As of right now, just upload the whole release folder, because I don't have the knowledge to set this up to
        # match patterns against whether it's a windows or linux release or not
        path: target/release
